version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sokubutsu_app_prod
    restart: always
    ports:
      - '${PORT:-3000}:3000'
    command: node dist/main.js
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    # 本番環境ではvolumeマウントしない（ビルド済みイメージを使用）
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
        reservations:
          memory: 256M
          cpus: "0.5"