version: '3.8'

services:
  sokubutsu-mvp:
    build: .
    container_name: sokubutsu-mvp
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--dns-result-order=ipv4first
    env_file:
      - .env
      - .env.production
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    # Webhook受信のため管理画面ポートを公開
    ports:
      - '3002:3002'
    healthcheck:
      test: ['CMD', 'node', '-e', "console.log('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
