# 開発環境用Docker Compose設定
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sokubutsu_app_dev
    restart: "no"  # 開発環境では自動再起動しない
    volumes:
      - .:/usr/src/app
      - node_modules_volume:/usr/src/app/node_modules
    ports:
      - '${PORT:-3000}:3000'
    command: npm run start:dev  # ホットリロード有効
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    # 開発用のログ設定
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

volumes:
  node_modules_volume: